import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Generic

from .report import SubroutineReportT
from .type_defs import SolutionT

# --- Data Structures ---


@dataclass
class SolutionRecord(Generic[SubroutineReportT, SolutionT]):
    """
    A data container for the output of a single subroutine execution, linking
    the performance report with the actual solution produced.
    """

    report: SubroutineReportT
    """The report detailing the subroutine's performance and metadata."""
    solution: SolutionT | None
    """
    The solution object generated by the subroutine.
    This can be None if the subroutine does not produce a new solution
    (e.g., configuration steps like 'set_random_seed').
    """


# --- Base Class ---


class SolutionManager(Generic[SubroutineReportT, SolutionT], ABC):
    """
    An abstract base class for managing the lifecycle of solutions during an
    optimization process.
    """

    def __init__(self) -> None:
        self.history: list[SolutionRecord[SubroutineReportT, SolutionT]] = []
        """
        The history of all subroutine executions, stored as a list of
        `SolutionRecord` objects.
        """

        self.best_solution: SolutionT | None = None
        """
        The best solution found so far during the optimization process.
        """
        self.best_obj_value: float | None = None
        """
        The best objective value found so far.
        """
        self.best_obj_bound: float | None = None
        """
        The best objective bound found so far.
        """

        self.ref_solution: SolutionT | None = None
        """
        The current reference solution, which may be used as a starting point
        for generating new candidate solutions.
        """
        self.ref_obj_value: float | None = None
        """
        The objective value of the current reference solution.
        """

    @abstractmethod
    def _get_obj_value(self, solution: SolutionT) -> float:
        """
        Extracts the objective value from a given solution object.
        """
        ...

    @abstractmethod
    def _a_is_better_obj_value(self, value_a: float, value_b: float | None) -> bool:
        """True if the first objective value is better than the second."""
        ...

    def best_obj_value_is_worse_than(self, new_value: float) -> bool:
        """Checks if the new objective value is worse than the best.

        Args:
            new_value (float): The new objective value to compare.

        Returns:
            bool: True if the new value is worse than the best objective value.
                Returns True if no best value is set yet (self.best_obj_value is None).
                Returns False if the new value is better than or equal to the best.
        """
        if self.best_obj_value is None:
            return True
        # Worse means strictly greater (for minimization)
        if new_value == self.best_obj_value:
            return False
        return not self._a_is_better_obj_value(new_value, self.best_obj_value)

    @abstractmethod
    def _a_is_better_obj_bound(self, bound_a: float, bound_b: float | None) -> bool:
        """True if the first objective bound is better than the second."""
        ...

    def best_obj_bound_is_worse_than(self, new_bound: float) -> bool:
        """Checks if the new objective bound is worse than the best.

        Args:
            new_bound (float): The new objective bound to compare.

        Returns:
            bool: True if the new bound is worse than the best objective bound.
                Returns True if no best bound is set yet (self.best_obj_bound is None).
                Returns False if the new bound is better than or equal to the best.
        """
        if self.best_obj_bound is None:
            return True
        # Worse means strictly greater (for minimization)
        if new_bound == self.best_obj_bound:
            return False
        return not self._a_is_better_obj_bound(new_bound, self.best_obj_bound)

    # Getters

    def get_best_solution(self) -> SolutionT | None:
        """Returns the best solution found so far."""
        return self.best_solution

    def has_best_solution(self) -> bool:
        """Checks if a valid best solution exists."""
        return self.best_solution is not None

    def get_ref_solution(self) -> SolutionT | None:
        """Returns the current reference solution (e.g., current in SA)."""
        return self.ref_solution

    def get_last_solution(self) -> SolutionT | None:
        """
        Retrieves the most recently generated valid solution from the history.
        """
        for record in reversed(self.history):
            if record.solution is not None:
                return record.solution
        return None

    def get_last_report(self) -> SubroutineReportT | None:
        """
        Retrieves the most recent report from the history.
        """
        if not self.history:
            return None
        return self.history[-1].report

    # Setters

    def register(
        self,
        report: SubroutineReportT,
        solution: SolutionT | None,
        force_update_ref_sol: bool = False,
    ) -> bool:
        """
        Registers the result of a subroutine, updates the history, and updates
        the best and reference solutions.

        Args:
            report (SubroutineReportT): The report generated by the subroutine.
            solution (SolutionT | None): The solution produced by the subroutine, if any.
            force_update_ref_sol (bool, optional): If True, ref_solution is always
                updated to the new solution. Otherwise, ref_solution is only updated
                if the new solution has a better objective value than the current best.
                Defaults to False.

        Raises:
            ValueError: If the reported objective value is inconsistent with the computed value.

        Returns:
            bool: True if the reference solution was updated by a better solution, False otherwise.
        """
        self.history.append(SolutionRecord(report=report, solution=solution))

        # Update objective bound if a new one is reported
        if report.obj_bound is not None:
            if self._a_is_better_obj_bound(report.obj_bound, self.best_obj_bound):
                self.best_obj_bound = report.obj_bound
                # logging.info(f"Objective bound updated: {self.best_obj_bound}")

        # Update solutions if a new solution is provided
        if solution is None:
            return False

        new_obj_value = self._get_obj_value(solution)
        if new_obj_value != report.obj_value:
            raise ValueError(
                "Inconsistent objective value: "
                f"computed {new_obj_value}, reported {report.obj_value}"
            )

        is_ref_updated = False

        if self._a_is_better_obj_value(new_obj_value, self.best_obj_value):
            self.best_solution = solution
            self.best_obj_value = new_obj_value
            is_ref_updated = True
            logging.info(
                f"Best & ref. solution updated with objective: {self.best_obj_value}"
            )
            self.ref_solution = solution
            self.ref_obj_value = new_obj_value
        elif force_update_ref_sol:
            is_ref_updated = self._a_is_better_obj_value(
                new_obj_value, self.ref_obj_value
            )
            self.ref_solution = solution
            self.ref_obj_value = new_obj_value
            logging.info("Ref. solution force-updated.")

        return is_ref_updated

    def sync_ref_to_best(self) -> None:
        """Sets reference_solution to the current best_solution, if exists."""
        if self.best_solution is not None:
            self.ref_solution = self.best_solution
            self.ref_obj_value = self.best_obj_value
            logging.info(
                f"Reference solution synced to best solution: obj={self.best_obj_value}"
            )

    def set_ref_solution(self, solution: SolutionT) -> None:
        """Manually sets the reference solution to a given solution."""
        self.ref_solution = solution
        self.ref_obj_value = self._get_obj_value(solution)
        logging.info(f"Reference solution manually set: obj={self.ref_obj_value}")
